name: Build docker images for develop

on:
  push:
    branches: master

jobs:
  build-base:
    uses: ./.github/workflows/build_tmpl.yml
    with:
      dir: "./base"
  build-avconv:
    uses: ./.github/workflows/build_tmpl.yml
    with:
      name: "avconv"
      dir: "./projects"
