name: Build docker images for develop

on:
  push:
    branches: master

jobs:
  build-base-gcc:
    uses: ./.github/workflows/build_tmpl.yml
    with:
      name: "gcc"
      dir: "./base"
      dockerfile: "gcc.dockerfile"
  build-base-clnag:
    uses: ./.github/workflows/build_tmpl.yml
    with:
      name: "clang"
      dir: "./base"
      dockerfile: "clang.dockerfile"
