on:
  workflow_call:
    inputs:
        name:
            type: string
        dir:
            required: true
            type: string

jobs:
  build-image-templ:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup docker builder
        uses: docker/setup-buildx-action@v3

      - name: Log in to ghcr.io
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}${{ inputs.name != '' && '-' || '' }}${{ inputs.name }}
          tags: latest

      - name: Build image ${{ inputs.name }}
        uses: docker/build-push-action@v6
        with:
          context: ./${{ inputs.dir }}
          push: true
          file: ${{ inputs.name }}.dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max