name: Build docker images for develop

on:
  push:
    branches: master

jobs:
  build-base:
    uses: ./.github/workflows/build_tmpl.yml
    with:
      dir: "./base"
      dockerfile: "gcc.dockerfile"
  build-avconv:
    needs: build-base
    uses: ./.github/workflows/build_tmpl.yml
    with:
      name: "avconv"
      dir: "./projects"
      dockerfile: "avconv.dockerfile"
